### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by anklebreaker** [nschloe/tuna#102]
Quick question, was getting a broken pipe message when running the tuna command. The tab opens up in browser but is unable to connect. Any idea on the cause?

```
Exception happened during processing of request from ('127.0.0.1', 63304)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tuna/main.py", line 64, in do_GET
    self.wfile.write(content)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```
Running on MacOS Catalina, Python 3.8 and Chrome

**Comment by nschloe** [comment]
No idea.

**Comment by zodman** [comment]
I have a fat project in django what take long time to start ... i generate the profile and tuna cannot open...

http://transfer.sh/1DKbkv6/cprofile.out

I generate the HTML files and the output was 2GB of HTML the unique tool it could open is cprofilev

**Comment by nschloe** [comment]
@zodman Please open a new issue for this.

**Comment by gabrielfougeron** [comment]
Hi. FYI, i got the same error as @anklebreaker running on wsl2 Windows11

**Comment by gjohnston9** [comment]
Same here :( My `.prof` file is 1.9M, not sure if this could be caused by too much data

**Comment by vschoener** [comment]
Same error on my side. 2.9 MB for the file. Seems maybe too complicated to handle using a request?

**Comment by martijnthe** [comment]
I came to tune after hitting [this limitation of snakeviz](https://github.com/jiffyclub/snakeviz/issues/112) -- thanks for filing that issue btw!

When loading a large-ish .prof file (2.9MiB), the browser tab crashes (out of memory?). I think the "Broken Pipe" is a consequence of the tab crashing, not the cause of it. FWIW, I tried it both with a recent Brave and Firefox. Same thing in both browsers.

A smaller .prof file (1MiB) loads OK, although it seems to bog down the browser quite a bit.

**Comment by gubenkoved** [comment]
Unfortunately unusable with my sample on 2.3 MiB of traces with the same symptom -- browser tab crashing and breaking the connection. It is able to render another sample with 700 KiB of data though.
```
Tuna: 0.5.11
Python: 3.10.6
OS: macOS 13.6.1
```

**Comment by bio-la** [comment]
same issue here, i got files of ~3MB. any idea how to get around this?

**Comment by NoAnyLove** [comment]
I think this issue is caused by the giant graph data generated in the HTML file. I tried with a 2.1MiB trace file and the browser crashed. I used `wget` to download the page directly, and the downloaded HTML file is as huge as 663MiB. It has 64 lines and one of them is an incredibly long `x-icicle` data. Even `vim` is struggling with opening this file.

Not sure if format the `x-icicle` data into multiple-lines would help with this issue, or probably it needs interactive partial loading like `snakeviz`?
