### ISSUE TITLE
Crash when the favicon does not exists

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [nschloe/tuna#115]
Hello, thank you for creating this module, I'm going to try to make my import faster using it  :)

I got the following error while monkey testing the server:
```
Exception happened during processing of request from ('127.0.0.1', 45132)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/pierre/pylint/venv/lib/python3.8/site-packages/tuna/main.py", line 63, in do_GET
    with open(filepath, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pierre/pylint/venv/lib/python3.8/site-packages/tuna/web/favicon.ico'
```

**Comment by nschloe** [comment]
No idea why it's looking for `favicon.ico`. If anything, it should be `favicon256.png`.

**Comment by FraserParlane** [comment]
+1 for this issue. There's also no `favicon256.png` in that folder. Only index.html and a static directory.

**Comment by nschloe** [comment]
I double-checked and `favicon256.png` _is_ shipped. No idea what should be wrong here.

**Comment by hugovk** [comment]
I can't reproduce this, I guess #120 fixed it.

**Comment by Pierre-Sassoulas** [comment]
I tried again it's working for me now.
