### ISSUE TITLE
assert mimetype is not None

### ISSUE THREAD

**Issue by emmanuelito** [nschloe/tuna#133]
Error / tuna 0.5.11 / installed with pip

```
Exception occurred during processing of request from ('192.168.64.1', 62031)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/scodoc/venv/lib/python3.9/site-packages/tuna/main.py", line 59, in do_GET
    assert mimetype is not None
AssertionError
```

**Comment by hugovk** [comment]
@emmanuelito How can this be reproduced?

**Comment by emmanuelito** [comment]
sorry, I do not remember, my report is from 4 years ago :-)

**Comment by nschloe** [comment]
Closing then.
