### ISSUE TITLE
AssertionError (line 98, in _shelf)

### ISSUE THREAD

**Issue by njzjz** [nschloe/tuna#53]
```
Traceback (most recent call last):
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/bin/tuna", line 10, in <module>
    sys.exit(main())
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/cli.py", line 31, in main
    start_server(args.infile, args.browser, args.port)
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/main.py", line 185, in start_server
    data = read(prof_filename)
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/main.py", line 26, in read
    return read_import_profile(filename)
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/main.py", line 165, in read_import_profile
    lst, k = _shelf(entries[::-1], 0)
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/main.py", line 99, in _shelf
    out[-1]["children"], k = _shelf(lst, k)
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/main.py", line 99, in _shelf
    out[-1]["children"], k = _shelf(lst, k)
  File "/home/jzzeng/anaconda3/envs/reacnetgenerator/lib/python3.7/site-packages/tuna/main.py", line 98, in _shelf
    assert level == reference_level + 1
AssertionError
```
[reacnetgenerator_importtime.log](https://github.com/nschloe/tuna/files/3665073/reacnetgenerator_importtime.log)

**Comment by nschloe** [comment]
Fixed in 0.3.2.
