### ISSUE TITLE
Exception occurred when running tuna program.prof

### ISSUE THREAD

**Issue by ma-sadeghi** [nschloe/tuna#73]
When I run `tuna program.prof`, I get the following exception along with many more warnings. I'm running `tuna` on Windows 10. Here's part of the log:
```
----------------------------------------
127.0.0.1 - - [26/Apr/2020 09:35:18] "GET /static/favicon256.png HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59291)
Traceback (most recent call last):
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\socketserver.py", line 724, in __init__
    self.handle()
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\http\server.py", line 406, in handle_one_request
    method()
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\site-packages\tuna\main.py", line 229, in do_GET
    mimetype, _ = mimetypes.guess_type(filepath)
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\mimetypes.py", line 291, in guess_type
    return _db.guess_type(url, strict)
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\mimetypes.py", line 116, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "C:\Users\Amin\Anaconda3\envs\py36\lib\urllib\parse.py", line 974, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object
----------------------------------------
```

**Comment by ma-sadeghi** [comment]
And these are part of the warnings I get:
```
WARNING:root:Didn't recognize and skipped line `   gH¯¼ڑٍ×ٹ>gH¯¼ڑٍ×ٹ>r   )r`
WARNING:root:Didn't recognize and skipped line `   r`
WARNING:root:Didn't recognize and skipped line `   gvƒ`
WARNING:root:Didn't recognize and skipped line `ôُ!”>gvƒ`
WARNING:root:Didn't recognize and skipped line `ôُ!”>©rŒ   éƒ   ع_legacy_cmpkey)i  i  g]ْ—¤2إ,?g]ْ—¤2إ,?©rŒ   rK  ع__str__)i~  i~  g<ھP“دل?g<ھP“دل?r  )r`
WARNING:root:Didn't recognize and skipped line `   r`
WARNING:root:Didn't recognize and skipped line `   gH¯¼ڑٍ×ٹ>gH¯¼ڑٍ×ٹ>rر  )r•   r•   gvƒ`
WARNING:root:Didn't recognize and skipped line `ôُ!¤>gvƒ`
WARNING:root:Didn't recognize and skipped line `ôُ!¤>0)r   r   ْ#<method 'insert' of 'list' objects>)r  r  g_eGô|÷>g_eGô|÷>{rش  )rل  rل  gâ2±-¨ô>gâ2±-¨ô>©ْMC:\Users\Amin\Anaconda3\envs\py36\lib\site-packages\scipy\special\__init__.pyi¤  rں  )r8   r8   gچيµ ÷ئہ>gچيµ ÷ئہ>©ْ1C:\Users\Amin\Anaconda3\envs\py36\lib\calendar.pyé2   ع_localized_month)r`
WARNING:root:Didn't recognize and skipped line `   r`
WARNING:root:Didn't recognize and skipped line `   g_eGô|§>g_eGô|§>0)r   r   ْ#<method 'extend' of 'list' objects>)i1  i1  g!»ءْْ@?gبـظ²×F?{©rت   i]  ع     _get_spec)rC  rC  gJà kW2ر>gJà kW2ر>)rت   i¬  r   )i  i  g5‌:è2?g„ڈز¶«،>?rط  )ri  ri  gصüBظ¥Wô>gصüBظ¥Wô>rك  )r¸   r¸   g?«ج”ضكز>g?«ج”ضكز>rم  )é4   r7  g­[NSdه>g­[NSdه>©ْEC:\Users\Amin\Anaconda3\envs\py36\lib\site-packages\numpy\__init__.pyéj   r   )r   r   gصƒ8إ™ه>gصƒ8إ™ه>©ْLC:\Users\Amin\Anaconda3\envs\py36\lib\site-packages\numpy\compat\__init__.pyr0   r   )r   r   gچيµ ÷ئ >gچيµ ÷ئ >©ْ/C:\Users\Amin\Anaconda3\envs\py36\lib\pickle.pyr#   r   )r`
WARNING:root:Didn't recognize and skipped line `   r`
WARNING:root:Didn't recognize and skipped line `   gvƒ`
WARNING:root:Didn't recognize and skipped line `ôُ!¤>gvƒ`
WARNING:root:Didn't recognize and skipped line `ôُ!¤>rْ  )r`
WARNING:root:Didn't recognize and skipped line `   r`
WARNING:root:Didn't recognize and skipped line `   g1Eîً2®>g1Eîً2®>)rR  r¾   ع_set_up_aliases)r   r   g_eGô|§>g_eGô|§>rV  )r`
WARNING:root:Didn't recognize and skipped line `   r`
WARNING:root:Didn't recognize and skipped line `   gH¯¼ڑٍ×ٹ>gH¯¼ڑٍ×ٹ>©ru  é*   r   )r`
WARNING:root:Didn't recognize and skipped line `   r`
```

**Comment by nschloe** [comment]
Can't reproduce without the profile file.

**Comment by ma-sadeghi** [comment]
There you go. I manually changed the file extension from `.prof` to `.log` so I can upload it here.
[program.log](https://github.com/nschloe/tuna/files/4536057/program.log)

**Comment by nschloe** [comment]
No problem running here:

![k](https://user-images.githubusercontent.com/181628/80315203-5cfcd700-87f6-11ea-8809-95047487e754.png)

**Comment by nschloe** [comment]
Looks similar to https://github.com/nschloe/tuna/issues/69#issuecomment-619148552 though.

**Comment by ma-sadeghi** [comment]
I see, maybe there's a dependency missing. Do I need to have any particular library installed on my machine? Like `npm`?

**Comment by nschloe** [comment]
Try upgrading to 0.4.3.

**Comment by ma-sadeghi** [comment]
0.4.3 fixed the error, and the browser shows something, but it doesn't seem to be right:
![image](https://user-images.githubusercontent.com/14086031/80427560-0787ff00-88b6-11ea-8d7e-af1e12758210.png)
I still see those warnings in cmd

**Comment by nschloe** [comment]
What's your Python version?

**Comment by ma-sadeghi** [comment]
3.6.10

**Comment by nschloe** [comment]
It's likely because of that. I wish I had an old Python version to reproduce.
